spring:
  output:
    ansi:
      enabled: always
  kafka:
    consumer:
      bootstrap-servers: kafka:9092

  datasource:
    url: jdbc:p6spy:h2:~/test;MODE=MySQL
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

gpt:
  api:
    url: https://api.openai.com
    key: ${GPT_API_KEY}

  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 100000
