spring:
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: kafka:9092

  datasource:
    url: jdbc:p6spy:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/riotdb?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

gpt:
  api:
    url: https://api.openai.com
    key: ${GPT_API_KEY}

  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 100000
